name: hdev
version: '0.1.0.0'
author: HaskellNixCabalStarter
maintainer: HaskellNixCabalStarter
license: MIT
dependencies:
- base
- typed-process
- yaml
- aeson
- bytestring
- directory
- filepath
- text
- unordered-containers
- containers
- hpack 
- optparse-applicative
executables:
  hdev:
    source-dirs: src
    main: Main.hs
  example:
    source-dirs: src
    main: ExampleMain.hs
    ghc-options:  -main-is ExampleMain
tests:
  hdev-test:
    main: Spec.hs
    source-dirs: 
    - test
    - src
    dependencies:
    - hspec
default-extensions: 
- LambdaCase
