name: HaskellNixCabalStarter
version: '0.1.0.0'
author: HaskellNixCabalStarter
maintainer: HaskellNixCabalStarter
license: MIT
dependencies:
- base
- typed-process
- yaml
- aeson
- bytestring
- directory
- filepath
- text
- unordered-containers
- containers
- hpack 
executables:
  hdev:
    source-dirs: src
    main: Main.hs
default-extensions: 
- LambdaCase
